#ifndef GL_TYPES_H
#define GL_TYPES_H
#include <gl/glew.h>
namespace KI
{
enum DATA_TYPE
{
	DATA_UNKNOWN = GL_NONE,
	DATA_INT = GL_INT,
	DATA_FLOAT = GL_FLOAT,
	DATA_UBYTE = GL_UNSIGNED_BYTE,
	DATA_USHORT = GL_UNSIGNED_SHORT,
	DATA_UINT = GL_UNSIGNED_INT,
};

enum MESH_TYPE
{
	MESH_POINTS = GL_POINTS,
	MESH_LINES = GL_LINES,
	MESH_LINE_LOOP = GL_LINE_LOOP,
	MESH_LINE_STRIP = GL_LINE_STRIP,
	MESH_TRIANGLE = GL_TRIANGLES,
	MESH_TRIANGLE_STRIP = GL_TRIANGLE_STRIP,
	MESH_TRIANGLE_FAN = GL_TRIANGLE_FAN

};

enum TEXTURE_TYPE
{
	TEXTURE_BUFFER = 1,
	TEXTURE_2D = GL_TEXTURE_2D,
};

}

#endif GL_TYPES_H