uniform uint u_num;
uniform uint u_bitShift;
layout(std430, binding = 0) readonly buffer InputBuffer {
    uint data[]; 
};

layout(std430, binding = 1) writeonly buffer OutputBuffer
{
	uint outData[];
};

layout(std430, binding = 2) readonly buffer OffsetBuffer {
    uint offset[]; 
};

void main()
{
	uint bin = gl_GlobalInvocationID.x;
	if(bin >= 256u){return;}

	uint outputIndex = offset[bin];
	for(uint index = 0u; index < u_num; ++index){
		uint value = (data[index] >> u_bitShift) & 0xFFu;
		if(value == bin){
			outData[outputIndex] = data[index];
			++outputIndex;
		}
	}
} 
