#version 430
uniform uint u_elementSize;
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D outImage;


void main()
{
	ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	
	vec4 value;
	value.x = float(texelCoord.x)/(gl_NumWorkGroups.x);
	value.y = float(texelCoord.y)/(gl_NumWorkGroups.y);
	value.z = 1.0;
	value.w = 1.0;
	imageStore(outImage,texelCoord,value);
} 